### ISSUE TITLE
Adjust slide layout/sizing for correct rendering of cytoscape networks

### ISSUE THREAD

**Issue by twesleyb** [cytoscape/cytoscape.js-reveal-slides#1]
I've found that the success/failure of rendering of a `cytoscape.js` network in a `reveal.js` slide seems to be dependent upon some global layout/size settings set by `Reveal.initialize`. For example, the following slide includes a cytoscape graph:
```html
<section>
    <h2>Style and Data</h2>
    <div id="graph1-cy" class="graph"></div>
</section>
```

these slides are globally configured as follows:
```js
Reveal.initialize({
			        // try to keep graphs working properly
				width: '100%',
				height: '100%',
				margin: 0,
				minScale: 1,
				maxScale: 1,
				transition: 'none',
...
```

I've found that these settings may not be ideal for other content slides, especially forcing `width` and `height` to `'100%'`. Is it possible to change these configuration settings on a slide-by-slide basis? Maybe I need to modify the underlying `custom.css` which contains the `graph` class?
```css
div.graph {
  border-width: 0.1em;
  border-style: solid;
  border-color: transparent;
  text-align: left;
  height: 80vh;
}
```
But, I've had no success adding/changing `height` or `width` parameters here.

**Comment by twesleyb** [comment]
A solution may be to modify the styling of the `div` element. To style `graph1-cy`, add the following to `custom.css`:
```css
#graph1-cy {
		margin: auto;
		width: 6em;
		height: 6em;
		display: flex;
		justify-content: center;
		border-radius: 50%;
		border: 0.1em solid white;
}
```
